#!/bin/bash
stdbuf -oL tail -f -n 0 'logs/<all>' |
awk -vq="'" -vb='\' -vchan="$1" '/\<https?:/ && $4 == "PRIVMSG" && $5 == chan && ! /nospoiler$/ {
  url = gensub(/.*\<http/,"http",1)
  sub(/ .*/,"",url)
  gsub(q, q b q q, url)
  cmd = "timeout 3 curl -A " q "Mozilla/5.0 (X11; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0" q \
        " -H " q "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" q \
        " -sL " q url q "| grep -ioP " q "< *title( [^>]*)?>" b "K[^<]*" q
  cmd | getline title
  close(cmd)
  gsub(/\r/, "", title)
  gsub(/&(nbsp|#160);/, " ", title)
  gsub(/&(lt|#60);/, "<", title)
  gsub(/&(le|#8804);/, "<=", title)
  gsub(/&(gt|#62);/, ">", title)
  gsub(/&(ge|#8805);/, ">=", title)
  gsub(/&(ne|#8800);/, "!=", title)
  gsub(/&(ndash|#8211);/, "-", title)
  gsub(/&(mdash|#8212);/, "--", title)
  gsub(/&(laquo|#171);/, "<<", title)
  gsub(/&(raquo|#187);/, ">>", title)
  gsub(/&(agrave|#224);/, "à", title)
  gsub(/&(aacute|#225);/, "á", title)
  gsub(/&(egrave|#232);/, "è", title)
  gsub(/&(eacute|#233);/, "é", title)
  gsub(/&(igrave|#236);/, "ì", title)
  gsub(/&(iacute|#237);/, "í", title)
  gsub(/&(ograve|#242);/, "ò", title)
  gsub(/&(oacute|#243);/, "ó", title)
  gsub(/&(ugrave|#249);/, "ù", title)
  gsub(/&(uacute|#250);/, "ú", title)
  gsub(/&(Agrave|#192);/, "À", title)
  gsub(/&(Aacute|#193);/, "Á", title)
  gsub(/&(Egrave|#200);/, "È", title)
  gsub(/&(Eacute|#201);/, "É", title)
  gsub(/&(Igrave|#204);/, "Ì", title)
  gsub(/&(Iacute|#205);/, "Í", title)
  gsub(/&(Ograve|#210);/, "Ò", title)
  gsub(/&(Oacute|#211);/, "Ó", title)
  gsub(/&(Ugrave|#217);/, "Ù", title)
  gsub(/&(Uacute|#218);/, "Ú", title)
  gsub(/&(copy|#169);/, "(c)", title)
  gsub(/&(reg|#174);/, "(R)", title)
  gsub(/&(trade|#8482);/, "(tm)", title)
  gsub(/&(apos|#39);/, q, title)
  gsub(/&(quot|#34);/, "\"", title)
  gsub(/&(amp|#38);/, "\\&", title)

  sub(/^ +/, "", title)
  sub(/ +$/, "", title)
  if (length(title)) print $4, $5, ":" title
  title = ""
  fflush()
}' > fifo
